import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App Iujuu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <p className='font-mono'>Probando la monospace</p>
      </main>
    </>
  )
}

export default Home
